services:
    PR\Bundle\RecaptchaBundle\Form\Type\RecaptchaType:
        public: true
        arguments:
            - '%pr_recaptcha.version%'
            - '%pr_recaptcha.public_key%'
            - '%pr_recaptcha.hide_badge%'
            - '%pr_recaptcha.host%'
        tags:
            - { name: form.type }

    PR\Bundle\RecaptchaBundle\Validator\Constraints\ContainsRecaptchaValidator:
        public: true
        arguments:
            - '%pr_recaptcha.enabled%'
            - '%pr_recaptcha.version%'
            - '%pr_recaptcha.secret_key%'
            - '%pr_recaptcha.score_threshhold%'
            - '@request_stack'
            - '@logger'
        tags:
            - { name: 'validator.constraint_validator', alias: 'pr_recaptcha.valid' }
